In [4]:
import numpy as np
a=np.genfromtxt("data.txt", delimiter=",")
print(a)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


In [12]:
np.ones((4,5), dtype="int16")
np.zeros((3, 5), dtype="int32")
x=np.array([1,2,3])
y=np.repeat(x, 3, axis=0)


In [6]:
import numpy as np
numstudents=int(input("Students: "))
numsubjects=int(input("Subjects: "))
marks=np.zeros((numstudents,numsubjects))
print(marks)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
import numpy as np
numstudents=int(input("Students: "))
numsubjects=int(input("Subjects: "))
marks=np.zeros((numstudents,numsubjects))


for i in range(0, numstudents):
    for j in range(0, numsubjects):
        marks[i,j]=int(input("Enter the grade:"))
        
print(marks)
        

S=np.sum(marks, axis=1, )
print(S)

[[56. 67.]
 [89. 90.]]
[123. 179.]
